-- HOUR: 날짤 데이터에서 시간만 추출/ HOUR(DATETIME) HOUR 열의 이름을 HOUR로 설정
SELECT HOUR(DATETIME) HOUR, COUNT(DATETIME) COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
HAVING HOUR >= 9 and HOUR <= 19
ORDER BY HOUR(DATETIME)
